name: Build & publish packages

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
          cache: maven
      - run: mvn -B package -Dspring-boot.build-image.publish=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up settings.xml for GitHub Packages
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          cache: maven

      - name: Publish the new version to GitHub Packages (skipping tests since we only deploy if the build workflow succeeded)
        run: mvn -B --no-transfer-progress package deploy -DskipTests -Dspring-boot.build-image.publish=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
